#!/bin/bash

USAGE() # some plan of the script, use "-h"
{
cat << EOF
usage: $0 options
./deployCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>

REQUIRED:
-p <port> The port that DNS server will bind to
-o <origin> The name of the origin server for CDN
-n <name> The CDN-specific name that server translates to an IP
-u <username> The account name used for logging in
-i <keyfile> path to the private key used for logging into nodes
EOF
}

#echo $*
while getopts p:o:n:u:i: args
do
	case $args in
		p)
			SERVER_PORT=$OPTARG
			#echo $SERVER_PORT
			;;
		o)
			ORIGIN_SERVER=$OPTARG
			#echo $ORIGIN_SERVER	
			;;
		n)
			CDN_NAME=$OPTARG
			#echo $CDN_NAME
			;;
		u)
			USER_NAME=$OPTARG 
			#echo $USER_NAME
			;;
		i)
			KEY_FILE=$OPTARG
			#echo $KEY_FILE
			;;
		*) # input is wrong
			USAGE
			exit 1 # break out
			;;
 	esac
done
shift $((OPTIND-1))

replica_hosts=(ec2-54-85-32-37.compute-1.amazonaws.com 
	ec2-54-193-70-31.us-west-1.compute.amazonaws.com 
	ec2-52-38-67-246.us-west-2.compute.amazonaws.com 
	ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
	ec2-52-29-65-165.eu-central-1.compute.amazonaws.com 
	ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
	ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com 
	ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
	ec2-54-233-185-94.sa-east-1.compute.amazonaws.com)

DNS_SERVER=cs5700cdnproject.ccs.neu.edu	
for REPLICA in "${replica_hosts[@]}"
do
    echo 'Close replica: ' $REPLICA
    ssh -i $KEY_FILE $USER_NAME@$REPLICA 'USER_NAME="$(whoami)"; killall --user $USER_NAME python'
done


echo "Close DNS server: " $DNS_SERVER
ssh -i $KEY_FILE $USER_NAME@$DNS_SERVER 'USER_NAME="$(whoami)"; killall --user $USER_NAME python3'



